FROM python:3.12-slim

ENV pythondontwrittenbythedoce=1
ENV pythonunbuffered=1
ENV debian_frontend=noninteractive

WORKDIR /ChazeFashion
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        && rm -rf /var/lib/apt/lists/*

RUN curl -fxsl https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

COPY requirements.txt /ChazeFashion/

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt


COPY . /ChazeFashion/

WORKDIR /ChazeFashion/theme/static_src
RUN npm install

RUN npm run build

WORKDIR /ChazeFashion

RUN mkdir -p /ChazeFashion/static /ChazeFashion/media

RUN python manage.py migrate

RUN python manage.py collectstatic --noinput

RUN adduser --disabled-password --gecos '' appuser \
    && chown -R appuser:appuser /ChazeFashion
USER appuser

EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/ || exit 1

CMD ["gunicorn", "--bind", "0.0.0.0.8000", "--workers", "3", "ChazeFashion.wsgi:application"]